sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t hadil2003/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hadil2003/docker-react npm run test