sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t hadilbelhaj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hadilbelhaj/docker-react npm run test