name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t hadil2003/react-test -f Dockerfile.dev .
      
      - name: Run tests
        run: docker run -e CI=true hadil2003/react-test npm run test
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontendreact
          environment_name: dockerenv
          existing_bucket_name: elasticbeanstalk-eu-north-1-646418206106 
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip