name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: |
          echo "Logging in to Docker Hub..."
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          if [ $? -eq 0 ]; then
            echo "Docker login successful"
          else
            echo "Docker login failed"
            exit 1
          fi
      
      - name: Build Docker image
        run: docker build -t hadil2003/react-test -f Dockerfile.dev .
      
      - name: Run tests
        run: docker run -e CI=true hadil2003/react-test npm test
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontendreact
          environment_name: dockerenv
          existing_bucket_name: elasticbeanstalk-eu-north-1-646418206106 
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip